"""adjust workout table

Revision ID: bcba78731ada
Revises: 30242712e8a2
Create Date: 2024-12-02 21:18:48.069185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bcba78731ada'
down_revision: Union[str, None] = '30242712e8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the column with nullable=True
    op.add_column('workout', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True))

    # Update all existing rows to have the name "Workout"
    op.execute("UPDATE workout SET name = 'Workout'")

    # Alter the column to set nullable=False
    op.alter_column('workout', 'name', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'name')
    # ### end Alembic commands ###
