"""fix exercise muscle group table

Revision ID: d7a9382781b8
Revises: 038189e3b761
Create Date: 2024-12-03 20:21:01.434676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7a9382781b8'
down_revision: Union[str, None] = '038189e3b761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercisemusclegroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['musclegroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercisemodelgroup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercisemodelgroup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('muscle_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='fk_exercisemodelgroup_exercise_id_exercise'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['musclegroup.id'], name='fk_exercisemodelgroup_muscle_group_id_musclegroup'),
    sa.PrimaryKeyConstraint('id', name='pk_exercisemodelgroup')
    )
    op.drop_table('exercisemusclegroup')
    # ### end Alembic commands ###
